{{ $namespace := .Release.Namespace }}
{{- $name := include "room-assistant.name" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "room-assistant.fullname" . }}-config
  labels:
    {{- include "room-assistant.labels" . | nindent 4 }}
data:
  config-setup.sh: |
    #!/bin/bash
    TEMPLATE_DIR=$1
    CONFIG_DIR=$2
    if [ -z "$LOCATION" ]; then
      echo "Required environment variable 'LOCATION' is missing"
      exit 1
    fi
    CLUSTER_WEIGHT=${WEIGHT:-50}

    sed -e "s/REPLACEME/$LOCATION/" -e "s/weight: .*$/weight: $CLUSTER_WEIGHT/" $TEMPLATE_DIR/local.yaml | tee $CONFIG_DIR/local.yaml
  local.yaml: |
    global:
      instanceName: REPLACEME
      integrations:
        {{- range .Values.global.integrations }}
        - {{ . }}
        {{- end }}
    {{- with .Values.homeAssistant }}
    homeAssistant:
      mqttUrl: '{{ .mqttUrl }}'
      mqttOptions:
        rejectUnauthorized: {{ .mqttOptions.rejectUnauthorized }}
        {{- if ne .mqttOptions.username ""}}
        username: {{ .mqttOptions.username }}
        {{- end }}
        {{- if ne .mqttOptions.password "" }}
        password: {{ .mqttOptions.password }}
        {{- end }}
      discoveryPrefix: {{ .discoveryPrefix }}
      sendAttributes: {{ .sendAttributes }}
      sendMqttRoom: {{ .sendMqttRoom }}
      mqttRoomPrefix: {{ .mqttRoomPrefix }}
    {{- end }}
    cluster:
      weight: 50
      quorum: {{ .Values.cluster.quorum }}
      autoDiscovery: {{ $.Values.cluster.autoDiscovery }}
      {{- if ne $.Values.cluster.autoDiscovery true }}
      peerAddresses:
        {{- range $location := .Values.locations }}
        - {{ $name }}-{{ $location.room }}.{{ $.Values.service.serviceDomain }}:{{ $.Values.service.clusterPort }}
        {{- end }}
      {{- end }}

    bluetoothLowEnergy:
      allowlist:
      {{- range .Values.bluetoothLowEnergy.allowlist }}
      - {{ . }}
      {{- end }}
      tagOverrides:
      {{- range $id, $name := .Values.bluetoothLowEnergy.tagOverrides }}
        {{ $id }}:
          {{ $name | toYaml }}
      {{- end }}
