{{- $fullname := include "room-assistant.fullname" . }}
{{- $relname := .Release.Name -}}
{{- $name := include "room-assistant.name" . }}
{{- $labels := include "room-assistant.labels" . }}
{{- range $location := .Values.locations }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{  $fullname }}-{{ $location.room }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $name }}-{{ $location.room }}.{{ $.Values.service.serviceDomain }}
  {{- with $.Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.clusterPort }}
      targetPort: cluster
      protocol: UDP
      name: cluster
  selector:
    app.kubernetes.io/name: {{ $name }}-{{ $location.room }}
    app.kubernetes.io/instance: {{ $relname }}
{{- end }}